# challenge-mdh-part1
challenge-mdh-part1

You have "errors.py" file.
Ð¡orrect the mistakes.

The result after run should be:
Here we go1
Here we go2
Here we go3
etc...
